/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../public/model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={54351.413} decay={2} position={[4.076, 5.904, -1.005]} rotation={[-1.839, 0.602, 1.932]} />
      <mesh geometry={nodes['C-KESP2W6565'].geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['C-KESP2W6565001'].geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['C-KESP2W6565002'].geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.End_Cap_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.End_Cap_2.geometry} material={materials['Material.002']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.End_Cap001_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.End_Cap001_2.geometry} material={materials['Material.002']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.End_Cap002_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.End_Cap002_2.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Infill001.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Infill002.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Infill003.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Infill004.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Infill005.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Infill006.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Infill007.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Infill008.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1001.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1002.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1003.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1004.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1005.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1006.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1007.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1008.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1009.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1010.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1011.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1012.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1013.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1014.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1015.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1030.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1031.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer001.geometry} material={materials['Material.001']} position={[0, 0, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer002.geometry} material={materials['Material.001']} position={[0, 0, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer003.geometry} material={materials['Material.001']} position={[0, 0.002, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer004.geometry} material={materials['Material.001']} position={[0, 0.002, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer005.geometry} material={materials['Material.001']} position={[0, 0, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer006.geometry} material={materials['Material.001']} position={[0, 0.001, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer007.geometry} material={materials['Material.001']} position={[0, 0, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer008.geometry} material={materials['Material.001']} position={[0, 0, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer009.geometry} material={materials['Material.001']} position={[0, 0, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer010.geometry} material={materials['Material.001']} position={[0, 0, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer011.geometry} material={materials['Material.001']} position={[0, 0, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer012.geometry} material={materials['Material.001']} position={[0, 0, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer013.geometry} material={materials['Material.001']} position={[0, 0, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer014.geometry} material={materials['Material.001']} position={[0, 0, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer015.geometry} material={materials['Material.001']} position={[0, 0, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer016.geometry} material={materials['Material.001']} position={[0, 0, 1.867]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer017.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer018.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer019.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer020.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer021.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer022.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer023.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer024.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer025.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer026.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer027.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer028.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer029.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer030.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer031.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer032.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer033.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer034.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer035.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer036.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer037.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer038.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer039.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer040.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer041.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer042.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer043.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer044.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer045.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer046.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer047.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer048.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer049.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer050.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer051.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer052.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer053.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer054.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer055.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer056.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer057.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer058.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer059.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer060.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer061.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer062.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer063.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Spacer064.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder001.geometry} material={materials['Material.019']} position={[0.775, 0.11, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder002.geometry} material={materials['Material.019']} position={[0.775, 0.284, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder003.geometry} material={materials['Material.019']} position={[0.775, 0.463, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder005.geometry} material={materials['Material.019']} position={[0.775, 0.637, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder004.geometry} material={materials['Material.019']} position={[0.775, 0.819, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder006.geometry} material={materials['Material.019']} position={[0.775, 0.993, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder007.geometry} material={materials['Material.019']} position={[0.775, 1.172, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder008.geometry} material={materials['Material.019']} position={[0.775, 1.346, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder009.geometry} material={materials['Material.019']} position={[0.775, 1.528, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder010.geometry} material={materials['Material.019']} position={[0.775, 1.703, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder011.geometry} material={materials['Material.019']} position={[0.775, 1.881, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder012.geometry} material={materials['Material.019']} position={[0.775, 2.056, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder013.geometry} material={materials['Material.019']} position={[0.775, 2.237, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder014.geometry} material={materials['Material.019']} position={[0.775, 2.412, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder015.geometry} material={materials['Material.019']} position={[0.775, 2.591, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder016.geometry} material={materials['Material.019']} position={[0.775, 2.765, -0.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder017.geometry} material={materials['Material.019']} position={[0.775, 0.11, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder018.geometry} material={materials['Material.019']} position={[0.775, 0.284, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder019.geometry} material={materials['Material.019']} position={[0.775, 0.463, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder020.geometry} material={materials['Material.019']} position={[0.775, 0.637, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder021.geometry} material={materials['Material.019']} position={[0.775, 0.819, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder022.geometry} material={materials['Material.019']} position={[0.775, 0.993, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder023.geometry} material={materials['Material.019']} position={[0.775, 1.172, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder024.geometry} material={materials['Material.019']} position={[0.775, 1.346, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder025.geometry} material={materials['Material.019']} position={[0.775, 1.528, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder026.geometry} material={materials['Material.019']} position={[0.775, 1.703, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder027.geometry} material={materials['Material.019']} position={[0.775, 1.881, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder028.geometry} material={materials['Material.019']} position={[0.775, 2.056, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder029.geometry} material={materials['Material.019']} position={[0.775, 2.237, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder030.geometry} material={materials['Material.019']} position={[0.775, 2.412, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder031.geometry} material={materials['Material.019']} position={[0.775, 2.591, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder032.geometry} material={materials['Material.019']} position={[0.775, 2.765, 1.822]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder033.geometry} material={materials['Material.019']} position={[0.775, 0.11, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder034.geometry} material={materials['Material.019']} position={[0.775, 0.284, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder035.geometry} material={materials['Material.019']} position={[0.775, 0.463, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder036.geometry} material={materials['Material.019']} position={[0.775, 0.637, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder037.geometry} material={materials['Material.019']} position={[0.775, 0.819, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder038.geometry} material={materials['Material.019']} position={[0.775, 0.993, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder039.geometry} material={materials['Material.019']} position={[0.775, 1.172, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder040.geometry} material={materials['Material.019']} position={[0.775, 1.346, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder041.geometry} material={materials['Material.019']} position={[0.775, 1.528, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder042.geometry} material={materials['Material.019']} position={[0.775, 1.703, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder043.geometry} material={materials['Material.019']} position={[0.775, 1.881, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder044.geometry} material={materials['Material.019']} position={[0.775, 2.056, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder045.geometry} material={materials['Material.019']} position={[0.775, 2.237, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder046.geometry} material={materials['Material.019']} position={[0.775, 2.412, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder047.geometry} material={materials['Material.019']} position={[0.775, 2.591, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder048.geometry} material={materials['Material.019']} position={[0.775, 2.765, 1.848]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder049.geometry} material={materials['Material.019']} position={[0.775, 0.11, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder050.geometry} material={materials['Material.019']} position={[0.775, 0.284, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder051.geometry} material={materials['Material.019']} position={[0.775, 0.463, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder052.geometry} material={materials['Material.019']} position={[0.775, 0.637, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder053.geometry} material={materials['Material.019']} position={[0.775, 0.819, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder054.geometry} material={materials['Material.019']} position={[0.775, 0.993, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder055.geometry} material={materials['Material.019']} position={[0.775, 1.172, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder056.geometry} material={materials['Material.019']} position={[0.775, 1.346, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder057.geometry} material={materials['Material.019']} position={[0.775, 1.528, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder058.geometry} material={materials['Material.019']} position={[0.775, 1.703, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder059.geometry} material={materials['Material.019']} position={[0.775, 1.881, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder060.geometry} material={materials['Material.019']} position={[0.775, 2.056, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder061.geometry} material={materials['Material.019']} position={[0.775, 2.237, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder062.geometry} material={materials['Material.019']} position={[0.775, 2.412, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder063.geometry} material={materials['Material.019']} position={[0.775, 2.591, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Rusty_Screw_Cylinder064.geometry} material={materials['Material.019']} position={[0.775, 2.765, 3.692]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.004, 0.004, 0.008]} />
      <mesh geometry={nodes.Slat_1032.geometry} material={materials['Material.001']} position={[0, 2.52, 3.673]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1033.geometry} material={materials['Material.001']} position={[0, 2.521, 3.673]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1034.geometry} material={materials['Material.001']} position={[0, 2.521, 3.673]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1035.geometry} material={materials['Material.001']} position={[0, 2.521, 3.673]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1036.geometry} material={materials['Material.001']} position={[0, 2.521, 3.673]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1037.geometry} material={materials['Material.001']} position={[0, 2.521, 3.673]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1038.geometry} material={materials['Material.001']} position={[0, 2.521, 3.673]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1039.geometry} material={materials['Material.001']} position={[0, 2.521, 3.673]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1040.geometry} material={materials['Material.001']} position={[0, 2.521, 3.673]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1041.geometry} material={materials['Material.001']} position={[0, 2.521, 3.673]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1042.geometry} material={materials['Material.001']} position={[0, 2.521, 3.673]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1043.geometry} material={materials['Material.001']} position={[0, 2.521, 3.673]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1044.geometry} material={materials['Material.001']} position={[0, 2.521, 3.673]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Slat_1045.geometry} material={materials['Material.001']} position={[0, 2.52, 3.673]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/model.glb')
